services:
  podmachine:
    build: .
    image: ghcr.io/reloadedhead/podmachine:latest
    container_name: podmachine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
      - podmachine_data:/data
    environment:
      TZ: UTC
    read_only: true
    tmpfs:
      - /tmp

volumes:
  podmachine_data:
